<h2><center>THE CHINESE UNIVERSITY OF HONG KONG<br /> 
    Department of Mathematics<br />
 MATH4280<br />
    Innovation and Design in Big Data Analytics</center></h2>

# Note 2<a id='top'></a>

- <a href='#section1'>2.1 Create a numpy array</a>
- <a href='#section2'>2.2 Size and shape of a numpy array</a>
- <a href='#section3'>2.3 Extract specific items from an array</a>
- <a href='#section4'>2.4 Create a new array from an existing array </a>
- <a href='#section5'>2.5  Reshaping and Flattening Multidimensional arrays</a>
- <a href='#section6'>2.6 Create sequences, repetitions and random numbers using numpy</a>
- <a href='#section7'>2.7 Get index locations that satisfy a given condition using `np.where`</a>
- <a href='#section8'>2.8 import and export data as a csv file</a>
- <a href='#section9'>2.9 Concatenate two numpy arrays columnwise and row wise</a>
- <a href='#section10'>2.10 Sort a numpy array based on one or more columns</a>
- <a href='#section11'>2.11 Advanced numpy functions</a>




# 2.1 Create a numpy array<a id='section1'></a>

There are multiple ways to create a numpy array, most of which will be covered as you read this. However one of the most common ways is to create one from a list or a list like an object by passing it to the np.array function.

In [1]:
# Create an 1d array from a list
import numpy as np
list1 = [0,1,2,3,4]
arr1d = np.array(list1)

# Print the array and its type
print(type(arr1d))
arr1d

<class 'numpy.ndarray'>


array([0, 1, 2, 3, 4])

# Caution

- Consider the order of clicking 'run' in a jupyter notebook.
- If you change the numpy variable in the later blocks, and for some reasons you scroll over and go to the code in the earlier block. 
- The effect you applied to the later block would affect the value of that related variables in the earlier block.

In [2]:
"""
In python, `+` operator for lists is used for concatenating 
lists, not for element-wise addition.
So : list1 + 2  doesn't work on list type variables
"""

# Instead, use np.array() to create an array from a list
# and then use the `+` operator for element-wise addition

arr1d + 2

array([2, 3, 4, 5, 6])

In [3]:
# Add 2 to each element of arr1d
arr1d / 2

array([0. , 0.5, 1. , 1.5, 2. ])

### Create a matrix like a 2d array.

In [4]:
# Create a 2d array from a list of lists
list2 = [[0,1,2], [3,4,5], [6,7,8]]
arr2d = np.array(list2)
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
    """To create 3d arrays, use a list of lists of lists, and so on.
    """
    
list_of_arrays = [
    [[0,1,2], [3,4,5], [6,7,8]],
    [[0,1,2], [3,4,5], [6,7,8]],
    [[0,1,2], [3,4,5], [6,7,8]]
]

arr3d = np.array(list_of_arrays)
arr3d

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]],

       [[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]],

       [[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

You may also specify the datatype by setting the dtype argument. Some of the most commonly used numpy dtypes are: 'float', 'int', 'bool', 'str' and 'object'.

To control the memory allocations you may choose to use one of ‘float32’, ‘float64’, ‘int8’, ‘int16’ or ‘int32’.

In [6]:
# float type arrays shows the decimal part of the numbers in the array.

arr2d_f = np.array(arr2d, dtype='float')
arr2d_f

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

The decimal point after each number is indicative of the float datatype. You can also convert it to a different datatype using the astype method.

In [7]:
# convert the float type array to int type array: 

arr2d_f.astype('int')

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
# Convert to int then to str datatype
arr2d_f.astype('int').astype('str')

array([['0', '1', '2'],
       ['3', '4', '5'],
       ['6', '7', '8']], dtype='<U11')

A numpy array must have all items to be of the same data type, unlike lists. This is another significant difference.

However, if you are uncertain about what datatype your array will hold or if you want to hold characters and numbers in the same array, you can set the dtype as 'object'.

In [9]:
# Create a boolean array
arr2d_b = np.array([1, 0, 10], dtype='bool')
arr2d_b

array([ True, False,  True])

## Inconsistent data type

- If we are putting elements that is not following the prior elements data tyoe, 
or having inconsistent data type. It would returns error: 


![Alt text](image.png)

In [10]:
# Create an object array to hold numbers as well as strings
arr1d_obj = np.array([1, 'a'], dtype='object')
arr1d_obj

array([1, 'a'], dtype=object)

### Convert an array back to a python list

In [11]:
# Convert an array back to a list
arr1d_obj.tolist()

[1, 'a']

<a href='#top'>jump to the top</a>

# 2.2 Size and shape of a numpy array<a id='section2'></a>

In [12]:
# Create a 2d array with 3 rows and 4 columns
list2 = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]]
arr2 = np.array(list2, dtype='float')
arr2

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [5., 6., 7., 8.]])

In [13]:
# shape
print('Shape: ', arr2.shape)

Shape:  (3, 4)


In [14]:
# dtype
print('Datatype: ', arr2.dtype)

Datatype:  float64


In [15]:
# size
print('Size: ', arr2.size)

Size:  12


In [16]:
# ndim
print('Num Dimensions: ', arr2.ndim)

Num Dimensions:  2


In [17]:
print(arr1d_obj.ndim)

1


<a href='#top'>jump to the top</a>

# 2.3 Extract specific items from an array<a id='section3'></a>

You can extract specific portions on an array using indexing starting with 0, something similar to how you would do with python lists.

But unlike lists, numpy arrays can optionally accept as many parameters in the square brackets as there is number of dimensions.

In [18]:
arr2

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [5., 6., 7., 8.]])

In [19]:
# Slicing an array

# the first variable m, is the row, the second varaiable is referring to the index of column.
# 'm:' means slicing the array from the beginning to the m+1th row. (Recall zero indexing)

arr2[1:] # the first variable means starting slice index. It means slicing the array from the beginning to the second row.

# '[1:]' means [1,inf) (Recall zero indexing)

array([[3., 4., 5., 6.],
       [5., 6., 7., 8.]])

In [20]:
arr2[:2] # the second  variable refers to the stop slice index. It means the slice won't include the row of the second index.

# '[:2]' means [0,2) (Recall zero indexing)

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.]])

In [21]:
# '1:2' is the intersection of the first and second index. It means slicing the array from the first row to the second row.
arr2[1:2]

# '[1:2]' means [1,2) (Recall zero indexing)

array([[3., 4., 5., 6.]])

In [22]:
# When working with 2D arrays, the first variable works as the row index, and the second variable works as the column index.

arr2[:2, 2:4]

# row: '[:2]' means [0,2) (Recall zero indexing)
# column: '[2:4]' means [2,4) (Recall zero indexing)

array([[3., 4.],
       [5., 6.]])

In [23]:
list2

[[1, 2, 3, 4], [3, 4, 5, 6], [5, 6, 7, 8]]

- We cannot do the same for list objects:

![Alt text](image-1.png)

### Boolean indexing

A boolean index array is of the same shape as the array-to-be-filtered and it contains only True and False values. The values corresponding to True positions are retained in the output.

In [24]:
arr2

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [5., 6., 7., 8.]])

In [25]:
# Get the boolean output by applying the condition to each element.

"""
In general, it is 'broadbasting', that 
"""

b = arr2 > 4
b

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [26]:
# Boolean indexing 

"""
In NumPy, when you use a boolean array to index another array, it's known as boolean indexing. 
This operation allows you to select elements from an array based on a corresponding boolean mask. 
Here's how it works in your example:
"""

arr2[b]

array([5., 6., 5., 6., 7., 8.])

<a href='#top'>jump to the top</a>

## 2.3.1 Reverse the rows and the whole array

In [27]:
arr2

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [5., 6., 7., 8.]])

In [28]:
# while ':' used for general array slicing, '::' is used for step-wise slicing.

In [29]:
# the slicing operation of the previous block won't change the original array: 

arr2

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [5., 6., 7., 8.]])

In [30]:
# "::2" is step-wise slicing. the number following the second colon is the step size.

arr2[::2] 

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [31]:
a = [1,2,3,4,5,6,7,8,9]
a[::3]


[1, 4, 7]

In [32]:
# we reverse the step-wise slicing could make us can reverse the array

arr2[::-1, ]

array([[5., 6., 7., 8.],
       [3., 4., 5., 6.],
       [1., 2., 3., 4.]])

In [33]:
# we reverse the step-wise slicing could make us can reverse the array

a[::-1]

[9, 8, 7, 6, 5, 4, 3, 2, 1]

In [34]:
arr2[: ,::-1]

array([[4., 3., 2., 1.],
       [6., 5., 4., 3.],
       [8., 7., 6., 5.]])

In [35]:
arr2

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [5., 6., 7., 8.]])

In [36]:
# Reverse the row and column positions
arr2[::-1, ::-1]

array([[8., 7., 6., 5.],
       [6., 5., 4., 3.],
       [4., 3., 2., 1.]])

## 2.3.2 Represent missing values and infinite

In [37]:
# Insert a nan and an inf
arr2[1,1] = np.nan  # not a number
arr2[1,2] = np.inf  # infinite
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 3., nan, inf,  6.],
       [ 5.,  6.,  7.,  8.]])

In [38]:
np.isnan(arr2)

array([[False, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [39]:
np.isinf(arr2)

array([[False, False, False, False],
       [False, False,  True, False],
       [False, False, False, False]])

In [40]:
# '|' means 'or' variable in numpy.

# Replace nan and inf with -1. Don't use arr2 == np.nan
missing_bool = np.isnan(arr2) | np.isinf(arr2)
arr2[missing_bool] = -1  # inserting elements based on boolean indexing.  
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 3., -1., -1.,  6.],
       [ 5.,  6.,  7.,  8.]])

## 2.3.3 Compute mean, min, max on the ndarray

In [41]:
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 3., -1., -1.,  6.],
       [ 5.,  6.,  7.,  8.]])

In [42]:
# mean, max and min
print("Mean value is: ", arr2.mean())
print("Max value is: ", arr2.max())
print("Min value is: ", arr2.min())

Mean value is:  3.5833333333333335
Max value is:  8.0
Min value is:  -1.0


In [43]:
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 3., -1., -1.,  6.],
       [ 5.,  6.,  7.,  8.]])

However, if you want to compute the minimum values row wise or column wise, use the np.amin version instead.

In [44]:
# Row wise and column wise min
print("Column wise minimum: ", np.amin(arr2, axis=0))
print("Row wise minimum: ", np.amin(arr2, axis=1))


Column wise minimum:  [ 1. -1. -1.  4.]
Row wise minimum:  [ 1. -1.  5.]


# 2.4 Create a new array from an existing array<a id='section4'></a>

If you just assign a portion of an array to another array, the new array you just created actually refers to the parent array in memory.

That means, if you make any changes to the new array, it will reflect in the parent array as well.

So to avoid disturbing the parent array, you need to make a copy of it using `copy()`. All numpy arrays come with the `copy()` method.

## Concept: View

- In NumPy, when you create a new array by slicing or subsetting an existing array, it doesn't always create a completely new copy of the data. Instead, it often creates a view into the original data. 
- A view is a way of looking at the same underlying data with a different shape or a different subset. This is done for efficiency reasons, as creating copies of large arrays can be memory-intensive and slow.

In [45]:
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 3., -1., -1.,  6.],
       [ 5.,  6.,  7.,  8.]])

In [46]:
# In numpy, assigning a slice of an array to another variable doesn't create a new array. It just create a 'view' of the original array.

arr2a = arr2[:2,:2]  
arr2a[:1, :1] = 100  # the range of element 'up-to' first row and first column, --> which means 0,0 element,  would be changed to 100.

# We can see the effect of 'manipulating' arr2a in arr2
arr2

array([[100.,   2.,   3.,   4.],
       [  3.,  -1.,  -1.,   6.],
       [  5.,   6.,   7.,   8.]])

In [47]:
# The changes, of course would affect the view variable arr2a as well
arr2a

array([[100.,   2.],
       [  3.,  -1.]])

## Creating independent copy if that is necessary: 

In [48]:
# Copy portion of arr2 to arr2b
arr2b = arr2[:2, :2].copy() # the slice means the range of elements from 0,0, selecting it to up to but not including index = 2, i.e. the third row and third column
arr2b[:1, :1] = 101   # change the value of 0,0 element to 101

# 101 will not reflect the value of 3rd row, 3rd column element value in arr2
arr2

array([[100.,   2.,   3.,   4.],
       [  3.,  -1.,  -1.,   6.],
       [  5.,   6.,   7.,   8.]])

In [49]:
# But it has changed arr2b

arr2b

array([[101.,   2.],
       [  3.,  -1.]])

In [50]:
arr2[:1,:1]=50
arr2

array([[50.,  2.,  3.,  4.],
       [ 3., -1., -1.,  6.],
       [ 5.,  6.,  7.,  8.]])

In [51]:
arr2b

array([[101.,   2.],
       [  3.,  -1.]])

In [52]:
arr2a

array([[50.,  2.],
       [ 3., -1.]])

<a href='#top'>jump to the top</a>

# 2.5 Reshaping and Flattening Multidimensional arrays<a id='section5'></a>

Reshaping is changing the arrangement of items so that shape of the array changes while maintaining the same number of dimensions.

Flattening, however, will convert a multi-dimensional array to a flat 1d array. And not any other shape.

First, let’s reshape the `arr2` array from $3\times4$ to $4\times3$ shape.

In [53]:
arr2

array([[50.,  2.,  3.,  4.],
       [ 3., -1., -1.,  6.],
       [ 5.,  6.,  7.,  8.]])

In [54]:
# Reshape a 3x4 array to 4x3 array
arr2.reshape(4, 3)

array([[50.,  2.,  3.],
       [ 4.,  3., -1.],
       [-1.,  6.,  5.],
       [ 6.,  7.,  8.]])

## 2.5.1 Difference between `flatten()` and `ravel()`

1. Return Type:

`flatten()`: This method returns a new one-dimensional array. It creates a copy of the original data, so any modifications to the flattened array do not affect the original array.
`ravel():` This method also returns a one-dimensional array, but it may return either a new array or a reference to the original data if possible. If it returns a reference, then modifications to the flattened array may affect the original array.

2. Memory Usage:

`flatten()`: It creates a new copy of the data, so it may consume additional memory, especially for large arrays.
`ravel()`: If possible, ravel() returns a view of the original data without copying it, which can be more memory-efficient. However, if a copy is required to ensure a contiguous array, it will make one.

3. Contiguity:

`flatten()`: The resulting array is always guaranteed to be a contiguous array, which means that the elements are stored in adjacent memory locations.
`ravel()`: It returns a view of the original data whenever possible, so it may or may not be a contiguous array.

In [55]:
# Flatten it to a 1d array
arr2.flatten()

array([50.,  2.,  3.,  4.,  3., -1., -1.,  6.,  5.,  6.,  7.,  8.])

In [56]:
# `.flatten()` creates a copy of the array, whereas `.ravel()` creates a view of the array.
# Changing the flattened array does not change parent
b1 = arr2.flatten()  
b1[0] = 100  

# changing b1 does not affect arr2
arr2

array([[50.,  2.,  3.,  4.],
       [ 3., -1., -1.,  6.],
       [ 5.,  6.,  7.,  8.]])

In [57]:
b1

array([100.,   2.,   3.,   4.,   3.,  -1.,  -1.,   6.,   5.,   6.,   7.,
         8.])

In [58]:
# Changing the raveled array changes the parent also.
b2 = arr2.ravel()  
b2[0] = 101  

# changing b2 changes arr2 also
arr2

array([[101.,   2.,   3.,   4.],
       [  3.,  -1.,  -1.,   6.],
       [  5.,   6.,   7.,   8.]])

In [59]:
# the element of 0,0 has been changed to 101 in b2. 
# But the difference to arr2 is that b2 is a 1d array, since we applied .ravel

b2 

array([101.,   2.,   3.,   4.,   3.,  -1.,  -1.,   6.,   5.,   6.,   7.,
         8.])

<a href='#top'>jump to the top</a>

# 2.6 Create sequences, repetitions and random numbers using numpy<a id='section6'></a>

In [60]:
# Lower limit is 0 be default
print(np.arange(5))  

[0 1 2 3 4]


In [61]:
# 0 to 9
print(np.arange(0, 10))  

[0 1 2 3 4 5 6 7 8 9]


In [62]:
# 0 to 9 with step of 2
print(np.arange(0, 10, 2))  

[0 2 4 6 8]


In [63]:
# 10 to 1, decreasing order
print(np.arange(10, 0, -1))

[10  9  8  7  6  5  4  3  2  1]


In [64]:
# without specifying negative steps won't work.
print(np.arange(10, 0, 1))

[]


In [65]:
# Returning evenly spaced numbers, over a specific interval.
# In this example, The number Start at 1 and end at 50. 
# And then it will fills evenly spaced values in-between those blocks.
np.linspace(start=1, stop=50, num=10)


array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

The `np.zeros` and `np.ones` functions lets you create arrays of desired shape where all the items are either 0’s or 1’s.

In [66]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [67]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

## 2.6.1 Create repeating sequences

- Two types of repeating: 

`np.tile` will repeat a whole list or array n times. Whereas, `np.repeat` repeats each item n times.

In [68]:
a = [1,2,3] 

# Repeat whole of 'a' two times
print('Tile:   ', np.tile(a, 4))

Tile:    [1 2 3 1 2 3 1 2 3 1 2 3]


In [69]:
# Repeat each element of 'a' two times
print('Repeat: ', np.repeat(a, 2))

Repeat:  [1 1 2 2 3 3]


## 2.6.2 Generate random numbers

The `random` module provides nice functions to generate random numbers (and also statistical distributions) of any given shape.



In [70]:
# Random numbers between [0,1) of shape 2,2
print(np.random.rand(2,2))

[[0.46618737 0.20711917]
 [0.56008683 0.70573443]]


In [71]:
# Normal distribution with mean=0 and variance=1 of shape 2,2
print(np.random.randn(2,2))

[[-0.59320991  0.07632457]
 [ 1.13666771 -0.14717703]]


In [72]:
# Random integers between [0, 10) of shape 2,2
print(np.random.randint(0, 10, size=[2,2]))

[[9 6]
 [1 2]]


In [73]:
# One random number between [0,1)
print(np.random.random())

0.615138637537794


In [74]:
# Random numbers between [0,1) of shape 2,2
print(np.random.random(size=[2,2]))

[[0.50954655 0.7371927 ]
 [0.83027671 0.95758225]]


In [75]:
# Pick 10 items from a given list, with equal probability
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10))  

['a' 'a' 'o' 'o' 'a' 'o' 'e' 'i' 'a' 'e']


In [76]:
# Pick 10 items from a given list with a predefined probability 'p'
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10, p=[0.3, .1, 0.1, 0.4, 0.1]))  # picks more o's

['o' 'o' 'a' 'i' 'a' 'o' 'a' 'o' 'o' 'u']


Now, everytime you run any of the above functions, you get a different set of random numbers.

## Fixate the set of random numbers, and store it at a variable

If you want to repeat the same set of random numbers every time, you need to set the seed or the random state. The see can be any value. The only requirement is you must set the seed to the same value every time you want to generate the same set of random numbers.

Once `np.random.RandomState` is created, all the functions of the `np.random` module becomes available to the created randomstate object.

In [77]:
# Create the random state
rn = np.random.RandomState(100) 
# Seed value is 100. 
# It means the random numbers generated by this random state will be 
# the same as the random numbers generated by another random state with seed value 100.

# Create random numbers between [0,1) of shape 2,2
print(rn.rand(2,2))

[[0.54340494 0.27836939]
 [0.42451759 0.84477613]]


In [78]:
# This is a legacy function. 
# Now we use another seed value, and set it to global numpy random state using np.random.seed().
np.random.seed(100)

# It turns out we get the same set of random numbers as the previous example.
print(np.random.rand(2,2))

[[0.54340494 0.27836939]
 [0.42451759 0.84477613]]


## 2.6.3 Get the unique items and the counts

In [79]:
# Create random integers of size 10 between [0,10)
np.random.seed(100)
arr_rand = np.random.randint(0, 10, size=10)
print(arr_rand)

[8 8 3 7 7 0 4 2 5 2]


In [80]:
# Get the unique items and their counts
uniqs, counts = np.unique(arr_rand, return_counts=True)
print("Unique items : ", uniqs)
print("Counts       : ", counts)

Unique items :  [0 2 3 4 5 7 8]
Counts       :  [1 2 1 1 1 2 2]


<a href='#top'>jump to the top</a>

# 2.7 Get index locations that satisfy a given condition using `np.where`<a id='section7'></a>

Previously you saw how to extract items from an array that satisfy a given condition. Boolean indexing, remember?

But sometimes we want to know the index positions of the items (that satisfy a condition) and do whatever you want with it.

`np.where` locates the positions in the array where a given condition holds true.

In [81]:
# Create an array
arr_rand = np.array([8, 8, 3, 7, 7, 0, 4, 2, 5, 2])
print("Array: ", arr_rand)

Array:  [8 8 3 7 7 0 4 2 5 2]


In [82]:
# Positions where value > 5
index_gt5 = np.where(arr_rand > 5)
print("Positions where value > 5: ", index_gt5)

Positions where value > 5:  (array([0, 1, 3, 4], dtype=int64),)


In [83]:
arr_rand.take(index_gt5)

array([[8, 8, 7, 7]])

In [84]:
arr_rand[index_gt5]

array([8, 8, 7, 7])

Thankfully, np.where also accepts 2 more optional arguments x and y. Whenever condition is true, ‘x’ is yielded else ‘y’.

Below, I try to create an array that will have the string ‘gt5’ whenever the condition is true, else, it will have ‘lt5’.

In [85]:
# If value > 5, then yield 'gt5' else 'le5'
np.where(arr_rand > 5, 'gt5', 'le5')

array(['gt5', 'gt5', 'le5', 'gt5', 'gt5', 'le5', 'le5', 'le5', 'le5',
       'le5'], dtype='<U3')

Let’s find the location of the maximum and minimum valjues as well.

In [86]:
# Location of the max
print('Position of max value: ', np.argmax(arr_rand))  

Position of max value:  0


In [87]:
# Location of the min
print('Position of min value: ', np.argmin(arr_rand))  

Position of min value:  5


<a href='#top'>jump to the top</a>

# 2.8 import and export data as a csv file<a id='section8'></a>

A standard way to import datasets is to use the np.genfromtxt function. It can import datasets from web URLs, handle missing values, multiple delimiters, handle irregular number of columns etc.

I
As an example, let’s try to read a .csv file from the below URL. Since all elements in a numpy array should be of the same data type, the last column which is a text will be imported as a ‘nan’ by default.

By setting the filling_values argument you can replace the missing values with something else.

In [88]:
# Turn off scientific notation
np.set_printoptions(suppress=True)  

# Import data from csv file url
path = 'https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv'
data = np.genfromtxt(path, delimiter=',', skip_header=1, filling_values=-999, dtype='float')
data[:3]  # see first 3 rows

array([[  18. ,    8. ,  307. ,  130. , 3504. ,   12. ,   70. ,    1. ,
        -999. ],
       [  15. ,    8. ,  350. ,  165. , 3693. ,   11.5,   70. ,    1. ,
        -999. ],
       [  18. ,    8. ,  318. ,  150. , 3436. ,   11. ,   70. ,    1. ,
        -999. ]])

That was neat. But did you notice all the values in last column has the same value ‘-999’?

That happened because, I had mentioned the. `dtype=’float’`. The last column in the file contained text values and since all the values in a numpy array has to be of the same `dtype`, `np.genfromtxt` didn’t know how to convert it to a float.

## 2.8.1 Handle datasets that has both numbers and text columns

- when we set datatype to be a specific type, the genfromtxt() won't return the data that is outside that data type. 
- Set 'datatype = none' to see that function return all data type values from the dataset.  

In [89]:
# data2 = np.genfromtxt(path, delimiter=',', skip_header=1, dtype='object')
data2 = np.genfromtxt(path, delimiter=',', skip_header=1, dtype=None)
data2[:3]  # see first 3 rows

C:\Users\kinla\AppData\Local\Temp\ipykernel_6560\911103563.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  data2 = np.genfromtxt(path, delimiter=',', skip_header=1, dtype=None)


array([(18., 8, 307., 130, 3504, 12. , 70, 1, b'"chevrolet chevelle malibu"'),
       (15., 8, 350., 165, 3693, 11.5, 70, 1, b'"buick skylark 320"'),
       (18., 8, 318., 150, 3436, 11. , 70, 1, b'"plymouth satellite"')],
      dtype=[('f0', '<f8'), ('f1', '<i4'), ('f2', '<f8'), ('f3', '<i4'), ('f4', '<i4'), ('f5', '<f8'), ('f6', '<i4'), ('f7', '<i4'), ('f8', 'S38')])

Finally, `np.savetxt` lets you export the array as a csv file.

In [90]:
# Save the array as a csv file
np.savetxt("out.csv", data, delimiter=",")

<a href='#top'>jump to the top</a>

# 2.9 Concatenate two numpy arrays columnwise and row wise<a id='section9'></a>

There are 3 different ways of concatenating two or more numpy arrays.

- Method 1: `np.concatenate` by changing the axis parameter to 0 and 1
- Method 2: `np.vstack` and `np.hstack`
- Method 3: `np.r_` and `np.c_`
All three methods provide the same output.

One key difference to notice is unlike the other 2 methods, both `np.r_` and `np.c_` use square brackets to stack arrays. But first, let me create the arrays to be concatenated.

In [91]:
a = np.zeros([4, 4])
b = np.ones([4, 4])
print(a)
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


- `concatenate()`: list of data, axis = 0): concatenate along `axis=0`.
- `vstack()`: achieving the same thing with short hand

- `np.r_`: a special indexing trick.concatenate arrays along the rows in a concise manner. 

In [92]:
# Vertical Stack Equivalents (Row wise)
np.concatenate([a, b], axis=0)  
np.vstack([a,b])  
np.r_[a,b] 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [93]:
# Horizontal Stack Equivalents (Coliumn wise)
np.concatenate([a, b], axis=1) 
np.hstack([a,b])  
np.c_[a,b]

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

Besides, you can use `np.r_` to create more complex number sequences in 1d arrays.

In [94]:
# When we use `r_` class, both 1d array and scalars can be cancatenate together.  

np.r_[[1,2,3], 0, 0, [4,5,6]]

array([1, 2, 3, 0, 0, 4, 5, 6])

## Dimensional inconsistency:

- If we put higher dimension array next to lower dimension array, it turns out returning error: 
![Alt text](image-2.png)

<a href='#top'>jump to the top</a>

# 2.10 Sort a numpy array based on one or more columns<a id='section10'></a>

In [95]:
arr = np.random.randint(1,6, size=[8, 4])
arr

array([[3, 3, 2, 1],
       [1, 5, 4, 5],
       [3, 1, 4, 2],
       [3, 4, 5, 5],
       [2, 4, 5, 5],
       [4, 4, 4, 2],
       [2, 4, 1, 3],
       [2, 2, 4, 3]])

In [96]:
# Sort each columns of arr
np.sort(arr, axis=0)

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [2, 3, 4, 2],
       [2, 4, 4, 3],
       [3, 4, 4, 3],
       [3, 4, 4, 5],
       [3, 4, 5, 5],
       [4, 5, 5, 5]])

## 2.10.1  Sort a numpy array based on 1 column using argsort

In [97]:
# Get the index positions that would sort the array
x = np.array([1, 10, 5, 2, 8, 9])
sort_index = np.argsort(x)

# The index position in x that would sort the array
print(sort_index)

[0 3 2 4 5 1]


How to interpret this?

In array ‘x’, the 0th item is the smallest, 3rd item is the second smallest and so on.

In [98]:
x[sort_index]

array([ 1,  2,  5,  8,  9, 10])

## Sorting 2D arrays

Now, in order to sort the original `arr`, I am going to do an argsort on the 1st column and use the resulting index positions to sort `arr`. See the code.

In [99]:
# Argsort the first column

# `arr[:,0]`: slice the array to be a m by 1 array.
# `arr[:,0].argsort()`: sort the array by the first column, and return the index of the sorted array.
sorted_index_1stcol = arr[:, 0].argsort()

# Sort 'arr' by first column without disturbing the integrity of rows
arr[sorted_index_1stcol]

array([[1, 5, 4, 5],
       [2, 4, 5, 5],
       [2, 4, 1, 3],
       [2, 2, 4, 3],
       [3, 3, 2, 1],
       [3, 1, 4, 2],
       [3, 4, 5, 5],
       [4, 4, 4, 2]])

To sort it in decreasing order, simply reverse the argsorted index.

In [100]:
# Descending sort
# `sorted_index_1stcol[::-1]]`: reverse the index of the sorted array.
arr[sorted_index_1stcol[::-1]]

array([[4, 4, 4, 2],
       [3, 4, 5, 5],
       [3, 1, 4, 2],
       [3, 3, 2, 1],
       [2, 2, 4, 3],
       [2, 4, 1, 3],
       [2, 4, 5, 5],
       [1, 5, 4, 5]])

## 2.10.2 Sort a numpy array based on 2 or more columns

You can do this using `np.lexsort` by passing a tuple of columns based on which the array should be sorted.

Just remember to place the column to be sorted first at the rightmost side inside the tuple.

In [101]:
# Sort by column 0, then by column 1
lexsorted_index = np.lexsort((arr[:, 1], arr[:, 0])) 
arr[lexsorted_index]

array([[1, 5, 4, 5],
       [2, 2, 4, 3],
       [2, 4, 5, 5],
       [2, 4, 1, 3],
       [3, 1, 4, 2],
       [3, 3, 2, 1],
       [3, 4, 5, 5],
       [4, 4, 4, 2]])

<a href='#top'>jump to the top</a>

# 2.11 Advanced numpy functions <a id='section11'></a>

## 2.11.1 vectorize – Make a scalar function work on vectors

In [102]:
# Define a scalar function
def foo(x):
    if x % 2 == 1:
        return x**2
    else:
        return x/2

In [103]:
# On a scalar
print('x = 10 returns ', foo(10))
print('x = 11 returns ', foo(11))

x = 10 returns  5.0
x = 11 returns  121


-  'vector' means the collection of numpy arrays (no matter how many dimensions it has)

- On a vector, doesn't work

![Alt text](image-3.png)

Let’s vectorize `foo()` so it will work on arrays.

In [104]:
# Vectorize foo(). Make it work on vectors.
foo_v = np.vectorize(foo, otypes=[float])

print('x = [10, 11, 12] returns ', foo_v([10, 11, 12]))
print('x = [[10, 11, 12], [1, 2, 3]] returns ', foo_v([[10, 11, 12], [1, 2, 3]]))

x = [10, 11, 12] returns  [  5. 121.   6.]
x = [[10, 11, 12], [1, 2, 3]] returns  [[  5. 121.   6.]
 [  1.   1.   9.]]


## 2.11.2 apply_along_axis – Apply a function column wise or row wise

In [105]:
# Create a 4x10 random array
np.random.seed(100)
arr_x = np.random.randint(1,10,size=[4,10])
arr_x

array([[9, 9, 4, 8, 8, 1, 5, 3, 6, 3],
       [3, 3, 2, 1, 9, 5, 1, 7, 3, 5],
       [2, 6, 4, 5, 5, 4, 8, 2, 2, 8],
       [8, 1, 3, 4, 3, 6, 9, 2, 1, 8]])

Let’s understand this by solving the following question:


How to find the difference of the maximum and the minimum value in each row?


Well, the normal approach would be to write a for-loop that iterates along each row and then compute the max-min in each iteration.

That sounds alright but it can get cumbersome if you want to do the same column wise or want to implement a more complex computation. Besides, it can consume more keystrokes.

You can do this elegantly using the numpy.apply_along_axis.

It takes as arguments:

1. Function that works on a 1D vector (fund1d)
2. Axis along which to apply func1d. For a 2D array, 1 is row wise and 0 is column wise.
3. Array on which func1d should be applied.

Let’s implement this.

In [106]:
arr_x

array([[9, 9, 4, 8, 8, 1, 5, 3, 6, 3],
       [3, 3, 2, 1, 9, 5, 1, 7, 3, 5],
       [2, 6, 4, 5, 5, 4, 8, 2, 2, 8],
       [8, 1, 3, 4, 3, 6, 9, 2, 1, 8]])

In [107]:
# Define func1d
def max_minus_min(x):
    return np.max(x) - np.min(x)

# Apply along the rows
print('Row wise: ', np.apply_along_axis(max_minus_min, 1, arr=arr_x))

# Apply along the columns
print('Column wise: ', np.apply_along_axis(max_minus_min, 0, arr=arr_x))

Row wise:  [8 8 6 8]
Column wise:  [7 8 2 7 6 5 8 5 5 5]


## 2.11.3 More Useful Functions

### Digitize
Use `np.digitize` to return the index position of the bin each element belongs to.

In [108]:
# Create the array and bins
x = np.arange(10)
bins = np.array([0, 3, 6, 9])

# Get bin allotments
np.digitize(x, bins)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4], dtype=int64)

### Clip
Use `np.clip` to cap the numbers within a given cutoff range. All number lesser than the lower limit will be replaced by the lower limit. Same applies to the upper limit also.

In [109]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
# Cap all elements of x to lie between 3 and 8
np.clip(x, 3, 8)

array([3, 3, 3, 3, 4, 5, 6, 7, 8, 8])

### Histogram and Bincount
Both `histogram()` and `bincount()` gives the frequency of occurences. But with certain differences.

While `histogram()` gives the frequency counts of the bins, `bincount()` gives the frequency count of all the elements in the range of the array between the min and max values. Including the values that did not occur.

In [111]:
# Bincount example
x = np.array([1,1,2,2,2,4,4,5,6,6,6]) # doesn't need to be sorted
np.bincount(x) # 0 occurs 0 times, 1 occurs 2 times, 2 occurs thrice, 3 occurs 0 times, ...

array([0, 2, 3, 0, 2, 1, 3], dtype=int64)

In [112]:
# Histogram example
counts, bins = np.histogram(x, [0, 2, 4, 6, 8])
print('Counts: ', counts)
print('Bins: ', bins)

Counts:  [2 3 3 3]
Bins:  [0 2 4 6 8]


<a href='#top'>jump to the top</a>