In [10]:
import numpy as np
from scipy import linalg

### 1. **Matrix Multiplication (Dot Product):**

**Notation:** $C = A \times B$ or $C = AB$

**Definition:** For matrices $A$ (size $m \times n$) and $B$ (size $n \times p$), the matrix product $C$ is computed as follows:
$$C_{ij} = \sum_{k=1}^{n} A_{ik} \times B_{kj}$$

**Use Case Scenarios:**
- **Linear Transformations:** Used in transformations and mappings.
- **System of Linear Equations:** Solving systems of linear equations using matrices.
- **Graph Theory:** Representing and analyzing graph connections.

In [11]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = np.dot(A, B)
print(C)

[[19 22]
 [43 50]]


**@ operator**: The @ operator in Python 3.5 and later is used for matrix multiplication, which is more readable and less verbose than the np.dot() function.

In [12]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = A @ B
print(C)

[[19 22]
 [43 50]]


### 2. **Element-wise Multiplication (Hadamard Product):**

**Notation:** $C = A \odot B$

**Definition:** For matrices $A$ and $B$ of the same size, the Hadamard product $C$ is calculated by multiplying corresponding elements of $A$ and $B$ element-wise.
$$C_{ij} = A_{ij} \times B_{ij}$$

**Use Case Scenarios:**
- **Component-wise Operations:** Applying operations independently to corresponding elements.
- **Weighted Operations:** Combining data with specific weights element-wise.

In [13]:
C = np.multiply(A, B)
print(C)

[[ 5 12]
 [21 32]]


`*` Operator:

The `*` operator performs element-wise multiplication when used with NumPy arrays. For example, if you have two arrays a and b, a * b will multiply corresponding elements of the arrays element-wise.

In [14]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = a * b  # Result: [4, 10, 18]

print(result)

[ 4 10 18]


### 3. **Matrix Transposition:**

**Notation:** $B = A^T$ or $B = A^{\text{transpose}}$

**Definition:** Transposes rows and columns of a matrix $A$. If $A$ is of size $m \times n$, then $B$ will be of size $n \times m$ where $B_{ij} = A_{ji}$.

**Use Case Scenarios:**
- **Changing Row to Column Vectors:** Useful for vector manipulations.
- **Symmetric Matrices:** Verifying and working with symmetric matrices.

In [15]:
B = np.transpose(A)
print(B)

[[1 3]
 [2 4]]


### 4. **Matrix Inversion:**

**Notation:** $B = A^{-1}$

**Definition:** For a square matrix $A$, if there exists a matrix $B$ such that $AB = BA = I$, where $I$ is the identity matrix, then $B$ is the inverse of $A$.

**Use Case Scenarios:**
- **Solving Linear Equations:** Used in solving systems of linear equations ($AX = B$).
- **Transformation Reversal:** Inverting transformations for data recovery.

In [16]:
B = linalg.inv(A)
print(B)

[[-2.   1. ]
 [ 1.5 -0.5]]


### 5. **Kronecker Product:**

**Notation:** $C = A \otimes B$

**Definition:** For matrices $A$ (size $m \times n$) and $B$ (size $p \times q$), the Kronecker product $C$ is a block matrix of size $(mp) \times (nq)$ formed by multiplying each element of $A$ with the matrix $B$.

**Use Case Scenarios:**
- **Expanding Systems:** Increasing the dimensionality of matrices for larger systems.
- **Quantum Computing:** Representing quantum states and operations.

In [17]:
C = np.kron(A, B)
print(C)

[[-2.   1.  -4.   2. ]
 [ 1.5 -0.5  3.  -1. ]
 [-6.   3.  -8.   4. ]
 [ 4.5 -1.5  6.  -2. ]]


### 6. **Outer Product:**

**Notation:** $C = \text{np.outer}(A, B)$

**Definition:** For vectors $A$ (size $m$) and $B$ (size $n$), the outer product $C$ is a matrix of size $m \times n$ where each element of $C$ is the product of the corresponding elements of $A$ and $B$.

**Use Case Scenarios:**
- **Outer Product Expansion:** Creating matrices from vector multiplication for various applications.
- **Covariance Matrix:** Calculating the covariance matrix of two datasets.
- **Signal Processing:** Convolution operations and filter design.


In [18]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

C = np.outer(A, B)
print(C)

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
