<h2><center>THE CHINESE UNIVERSITY OF HONG KONG<br /> 
    Department of Mathematics<br />
 MATH4280<br />
    Innovation and Design in Big Data Analytics</center></h2>

# LAB ASSIGNMENT ACTIVITY 2

In [11]:
import pandas as pd
import numpy as np

# Question 1
## How to find all the local minima (or troughs) in a 1d array?
Write a function to find all the troughs in a 1D numpy array `a`. Troughs are points surrounded by larger values on both sides.

(Hence elements at both ends will not be considered as troughs in any case.)

1st Example input:

```
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
```

1st Example output:

```
 array([3, 6])
```

where, 3 and 6 are the positions of peak values 1 and 0.

2nd Example input:

```
np.random.seed(100)
a = np.random.randint(10, size=100)
```

2nd Example output:

```
array([ 2,  5,  7, 13, 16, 19, 21, 23, 26, 32, 37, 41, 45, 47, 49, 51, 54,
       56, 58, 60, 62, 66, 68, 75, 77, 79, 82, 84, 88, 90], dtype=int64)
```


In [12]:
## answer 1
np.random.seed(100)
a = np.random.randint(10,size=100)

def find_troughs(a):
    doublediff = np.diff(np.sign(np.diff(a)))
    trough_locations = np.where(doublediff == 2)[0] + 1
    return trough_locations
trough_locations = find_troughs(a)
trough_locations

array([ 2,  5,  7, 13, 16, 19, 21, 23, 26, 32, 37, 41, 45, 47, 49, 51, 54,
       56, 58, 60, 62, 66, 68, 75, 77, 79, 82, 84, 88, 90])

# Question 2
## How to change the order of columns of a dataframe?

Enter


In [13]:
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
df.head()

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

## Question 2a
In `df`, interchange columns `'a'` and `'c'`.

In [14]:
## answer 2a
df1=df[list('cbade')]
df1


c   b   a   d   e
0   2   1   0   3   4
1   7   6   5   8   9
2  12  11  10  13  14
3  17  16  15  18  19

## Question 2b

Create a generic function to interchange two columns, without hardcoding column names. 

i.e. a function that takes three arguments (dataframe, column name 1,  column name 2) and outputs the resultant dataframe.

In [15]:
## answer 2b
def switch_columns(df, col1=None, col2=None):
    colnames = df.columns.tolist()
    i1, i2 = colnames.index(col1), colnames.index(col2)
    colnames[i2], colnames[i1] = colnames[i1], colnames[i2]
    return df[colnames]

df2 = switch_columns(df, 'a', 'c')
df2

c   b   a   d   e
0   2   1   0   3   4
1   7   6   5   8   9
2  12  11  10  13  14
3  17  16  15  18  19

## Question 2c
Sort the columns in reverse alphabetical order, that is colume `'e'` first through column `'a'` last.

In [16]:
## answer 2c
df3=df[sorted(df.columns,reverse=True)]
df3


e   d   c   b   a
0   4   3   2   1   0
1   9   8   7   6   5
2  14  13  12  11  10
3  19  18  17  16  15

## Question 3

## How to create a new column that contains the row number of nearest column by euclidean distance?

Create a new column such that, each row contains the row number of nearest row-record by euclidean distance.

Enter

In [17]:
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1), columns=list('pqrs'), index=list('abcdefghij'))
df

p   q   r   s
a  59  40  95  52
b  31  67  25  56
c  18  46  90  46
d  36  17  13  87
e  83  68  93  96
f  21  11   9  90
g  73  31  13  19
h  94  93  45  58
i   1  74  55  93
j  67  17   6  52

Example output:

```
       p	q	r	s	nearest_row	dist
a	28	6	45	72	j	       0
b	18	48	57	30	i	       50
c	70	40	64	32	g	       45
d	27	13	79	89	a,j	       39
e	88	83	54	88	h	       67
f	46	18	79	1	c	       47
g	54	69	85	9	c	       45
h	56	32	36	65	i	       23
i	41	27	25	53	h	       23
j	28	6	45	72	a	       0
 ```

In [21]:
# Import required libraries
import numpy as np
import pandas as pd

# Set a seed for reproducibility
np.random.seed(100)

# Create a DataFrame with random integer values
df = pd.DataFrame(np.random.randint(1, 100, 40).reshape(10, -1), columns=list('pqrs'), index=list('abcdefghij'))
print(df)

# Initialize empty lists to store nearest rows and their distances
nearest_rows = []
nearest_distance = []

# Iterate over each row in the DataFrame
for i, row in df.iterrows():
    curr = row
    # Exclude the current row from the DataFrame
    rest = df.drop(i)
    # Dictionary to store Euclidean distances between the current row and others
    e_dists = {}
    # Iterate over the remaining rows to calculate Euclidean distances
    for j, contestant in rest.iterrows():
        # Calculate Euclidean distance using numpy's linalg.norm function
        e_dists.update({j: (np.linalg.norm(curr.values - contestant.values))})

    # Find the minimum Euclidean distance and corresponding row(s)
    min_dist = min(e_dists.values())
    nearest_row = [k for k, v in e_dists.items() if v == min_dist]  
    nearest_rows.append(','.join(nearest_row))  # Join list into a string
    nearest_distance.append(min_dist)

# Add new columns to the DataFrame for nearest row(s) and their distances
df['nearest_row'] = nearest_rows
df['dist'] = nearest_distance

# Print the updated DataFrame with additional columns
print(df)


    p   q   r   s
a   9  25  68  88
b  80  49  11  95
c  53  99  54  67
d  99  15  35  25
e  16  61  59  17
f  10  94  87   3
g  28   5  32   2
h  14  84   5  92
i  60  68   8  50
j  48  66  62  15
    p   q   r   s nearest_row       dist
a   9  25  68  88           e  80.417660
b  80  49  11  95           i  52.867760
c  53  99  54  67           i  58.438001
d  99  15  35  25           g  75.359140
e  16  61  59  17           j  32.588341
f  10  94  87   3           e  45.880279
g  28   5  32   2           e  65.069194
h  14  84   5  92           i  64.381674
i  60  68   8  50           b  52.867760
j  48  66  62  15           e  32.588341


# Question 4
## How to split a text column into two separate columns?


Enter

In [19]:
df = pd.DataFrame(["STD, City   State",
"33, Kolkata,West Bengal",
"44, Chennai,Tamil Nadu",
"40, Hyderabad,Telengana",
"80, Bangalore,Karnataka"], columns=['row'])
print(df)

                       row
0        STD, City   State
1  33, Kolkata,West Bengal
2   44, Chennai,Tamil Nadu
3  40, Hyderabad,Telengana
4  80, Bangalore,Karnataka


Split the string column in df to form a dataframe with 3 columns as shown.

Example output:

```
  STD        City        State
0  33     Kolkata  West Bengal
1  44     Chennai   Tamil Nadu
2  40   Hyderabad    Telengana
3  80   Bangalore    Karnataka
```

In [20]:
# Answer 4

df_out = df.row.str.split(',|   ', expand=True)
# Make first row as header
new_header = df_out.iloc[0]
df_out = df_out[1:]
df_out.columns = list(new_header)
df_out.reset_index(drop=True, inplace=True)
print(df_out)

  STD        City        State
0  33     Kolkata  West Bengal
1  44     Chennai   Tamil Nadu
2  40   Hyderabad    Telengana
3  80   Bangalore    Karnataka
