## 1. Instantiate a numpy array

In [7]:
import numpy as np

# Method 1: Creating an array from a Python list
array_from_list = np.array([1, 2, 3, 4, 5])
print("Command: array_from_list = np.array([1, 2, 3, 4, 5])")
print("Array created from list:", array_from_list)

# Method 2: Creating an array with a specific shape full of zeros
array_zeros = np.zeros((3, 4))  # 3 rows, 4 columns
print("Command: array_zeros = np.zeros((3, 4))")
print("Array of zeros:")
print(array_zeros)

# Method 3: Creating an array with a specific shape full of ones
array_ones = np.ones((2, 3))  # 2 rows, 3 columns
print("Command: array_ones = np.ones((2, 3))")
print("Array of ones:")
print(array_ones)

# Method 4: Creating an identity matrix
identity_matrix = np.eye(3)  # 3x3 identity matrix
print("Command: identity_matrix = np.eye(3)")
print("Identity matrix:")
print(identity_matrix)

# Method 5: Creating an array with a range of values
array_range = np.arange(1, 11, 2)  # Start at 1, stop before 11, step by 2
print("Command: array_range = np.arange(1, 11, 2)")
print("Array using arange:")
print(array_range)

# Method 6: Creating an array with evenly spaced values
array_linspace = np.linspace(0, 1, 5)  # Start at 0, end at 1, with 5 values in between
print("Command: array_linspace = np.linspace(0, 1, 5)")
print("Array using linspace:")
print(array_linspace)

# Method 7: Creating a random array
random_array = np.random.rand(2, 3)  # 2 rows, 3 columns with random values between 0 and 1
print("Command: random_array = np.random.rand(2, 3)")
print("Random array:")
print(random_array)

# Method 8: Creating an empty array (without initializing its values)
empty_array = np.empty((2, 2))
print("Command: empty_array = np.empty((2, 2))")
print("Empty array:")
print(empty_array)


Command: array_from_list = np.array([1, 2, 3, 4, 5])
Array created from list: [1 2 3 4 5]
Command: array_zeros = np.zeros((3, 4))
Array of zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Command: array_ones = np.ones((2, 3))
Array of ones:
[[1. 1. 1.]
 [1. 1. 1.]]
Command: identity_matrix = np.eye(3)
Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Command: array_range = np.arange(1, 11, 2)
Array using arange:
[1 3 5 7 9]
Command: array_linspace = np.linspace(0, 1, 5)
Array using linspace:
[0.   0.25 0.5  0.75 1.  ]
Command: random_array = np.random.rand(2, 3)
Random array:
[[0.64549877 0.36460012 0.24353327]
 [0.94493245 0.03430064 0.878143  ]]
Command: empty_array = np.empty((2, 2))
Empty array:
[[0.25 0.5 ]
 [0.75 1.  ]]


## 2. When we need to explicitly define the matrix?

In Python, you do not necessarily need to explicitly instantiate variables before using them. 
- Integers / floating point numbers
- Strings
- Boolean
- Lists
- Tuples
- Dictionaries
- Sets

There are only two cases we need to instantiate variables before using it:


### A. Non-basic variables

But when it comes to "non-basic data types", such as numpy arrays, we still need to instantiate it. 
We create a new zeros like array like the following:

In [4]:
import numpy as np 

xR = np.zeros_like(10)
print(xR)

0


With `np.zero_like()` in this example, we explicitly define xR, and the method returns a numpy array to the variable. 

### B. Instantiate iterables before loops

In some cases, you might want to instantiate variables, especially when you are using them as containers for processed data or if you want to define an empty data structure to populate it later.

In [ ]:
result_list = []  # Instantiate an empty list

for i in range(5):
    result_list.append(i * 2)  # Add processed data to the list

print(result_list)  # Output: [0, 2, 4, 6, 8]