In [3]:
import numpy as np
import pandas as pd
import numpy.linalg as la
from sklearn.decomposition import PCA
from sklearn.preprocessing import normalize

In [4]:
X = np.array([
    [4, 4, 0, 0],
    [3, 3, 0, 0],
    [5, 5, 0, 0],
    [0, 0, 3, 3],
    [0, 0, 2, 2],
    [0, 0, 5, 5],
])
m, n = X.shape

In [5]:
U, s, Vh = la.svd(X, full_matrices=False)
Sigma = np.diag(s)

U.shape, s.shape, Sigma.shape, Vh.shape

((6, 4), (4,), (4, 4), (4, 4))

In [6]:
k = 2

In [7]:
(U * s).round(2)

array([[-5.66,  0.  ,  0.  , -0.  ],
       [-4.24,  0.  , -0.  , -0.  ],
       [-7.07,  0.  , -0.  ,  0.  ],
       [ 0.  , -4.24,  0.  ,  0.  ],
       [ 0.  , -2.83,  0.  ,  0.  ],
       [ 0.  , -7.07,  0.  , -0.  ]])

In [8]:
(U[:,:k] * s[:k]).round(2)

array([[-5.66,  0.  ],
       [-4.24,  0.  ],
       [-7.07,  0.  ],
       [ 0.  , -4.24],
       [ 0.  , -2.83],
       [ 0.  , -7.07]])

In [9]:
(Vh.T * s).round(2)

array([[-7.07, -0.  , -0.  ,  0.  ],
       [-7.07, -0.  ,  0.  ,  0.  ],
       [-0.  , -6.16,  0.  , -0.  ],
       [-0.  , -6.16,  0.  ,  0.  ]])

In [10]:
(Vh[:k].T * s[:k]).round(2)

array([[-7.07, -0.  ],
       [-7.07, -0.  ],
       [-0.  , -6.16],
       [-0.  , -6.16]])

In [11]:
eb_u = U[:,:k] * s[:k]
(eb_u).round(2)

array([[-5.66,  0.  ],
       [-4.24,  0.  ],
       [-7.07,  0.  ],
       [ 0.  , -4.24],
       [ 0.  , -2.83],
       [ 0.  , -7.07]])

In [12]:
eb_m = Vh[:k].T
(eb_m).round(2)

array([[-0.71, -0.  ],
       [-0.71, -0.  ],
       [-0.  , -0.71],
       [-0.  , -0.71]])

In [13]:
(eb_u @ eb_m.T)

array([[4., 4., 0., 0.],
       [3., 3., 0., 0.],
       [5., 5., 0., 0.],
       [0., 0., 3., 3.],
       [0., 0., 2., 2.],
       [0., 0., 5., 5.]])

In [14]:
X

array([[4, 4, 0, 0],
       [3, 3, 0, 0],
       [5, 5, 0, 0],
       [0, 0, 3, 3],
       [0, 0, 2, 2],
       [0, 0, 5, 5]])

In [15]:
eb_u.round(2)

array([[-5.66,  0.  ],
       [-4.24,  0.  ],
       [-7.07,  0.  ],
       [ 0.  , -4.24],
       [ 0.  , -2.83],
       [ 0.  , -7.07]])

In [16]:
(X @ eb_m).round(2)

array([[-5.66,  0.  ],
       [-4.24,  0.  ],
       [-7.07,  0.  ],
       [ 0.  , -4.24],
       [ 0.  , -2.83],
       [ 0.  , -7.07]])

In [17]:
pca = PCA(n_components=k)
X_mean = X.mean(axis=0)
X_nrm = X - X_mean
X_nrm.round(2)

array([[ 2.  ,  2.  , -1.67, -1.67],
       [ 1.  ,  1.  , -1.67, -1.67],
       [ 3.  ,  3.  , -1.67, -1.67],
       [-2.  , -2.  ,  1.33,  1.33],
       [-2.  , -2.  ,  0.33,  0.33],
       [-2.  , -2.  ,  3.33,  3.33]])

In [18]:
U_, s_, Vh_ = la.svd(X_nrm, full_matrices=False)

In [19]:
(pca.fit_transform(X_nrm)).round(2)

array([[-3.68,  0.12],
       [-2.62, -0.82],
       [-4.74,  1.06],
       [ 3.37, -0.47],
       [ 2.43, -1.53],
       [ 5.25,  1.64]])

In [20]:
eb_u_ = U_[:, :k]*s_[:k]
(eb_u_).round(2)

array([[-3.68,  0.12],
       [-2.62, -0.82],
       [-4.74,  1.06],
       [ 3.37, -0.47],
       [ 2.43, -1.53],
       [ 5.25,  1.64]])

In [21]:
eb_m_ = Vh_[:k].T
(eb_m_).round(2)

array([[-0.53,  0.47],
       [-0.53,  0.47],
       [ 0.47,  0.53],
       [ 0.47,  0.53]])

In [22]:
(pca.components_).round(2)

array([[-0.53, -0.53,  0.47,  0.47],
       [ 0.47,  0.47,  0.53,  0.53]])

In [23]:
(eb_u_ @ eb_m_.T).round(2)

array([[ 2.  ,  2.  , -1.67, -1.67],
       [ 1.  ,  1.  , -1.67, -1.67],
       [ 3.  ,  3.  , -1.67, -1.67],
       [-2.  , -2.  ,  1.33,  1.33],
       [-2.  , -2.  ,  0.33,  0.33],
       [-2.  , -2.  ,  3.33,  3.33]])

In [24]:
(X_nrm).round(2)

array([[ 2.  ,  2.  , -1.67, -1.67],
       [ 1.  ,  1.  , -1.67, -1.67],
       [ 3.  ,  3.  , -1.67, -1.67],
       [-2.  , -2.  ,  1.33,  1.33],
       [-2.  , -2.  ,  0.33,  0.33],
       [-2.  , -2.  ,  3.33,  3.33]])

In [25]:
(eb_u_).round(2)

array([[-3.68,  0.12],
       [-2.62, -0.82],
       [-4.74,  1.06],
       [ 3.37, -0.47],
       [ 2.43, -1.53],
       [ 5.25,  1.64]])

In [26]:
(X_nrm @ eb_m_).round(2)

array([[-3.68,  0.12],
       [-2.62, -0.82],
       [-4.74,  1.06],
       [ 3.37, -0.47],
       [ 2.43, -1.53],
       [ 5.25,  1.64]])